### ISSUE TITLE
JIT does not compile with gcc-5.4

### ISSUE THREAD

**Issue by pdbain-ibm** [ibmruntimes/openj9-openjdk-jdk9#9]
c -DJAVA_SPEC_VERSION=9 -O3 -fno-strict-aliasing -g -MMD -DLINUX -D_REENTRANT -D_FILE_OFFSET_BITS=64  -fPIC  -DIPv6_FUNCTION_SUPPORT -DJ9HAMMER -m64 -Wimplicit -Wreturn-type -Werror -I. -I../include -I../oti -I../util -I../gc_include -I/home/pdbain/github/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/omr/gc/include -I../tr.source/runtime -I../tr.source/codegen -I../tr.source/base -I../tr.source/trj9/runtime -I../nls -I/home/pdbain/github/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/omr/include_core  -DTR_HOST_X86 -DTR_64Bit -DTR_HOST_64BIT -DTR_TARGET_64BIT -DTR_TARGET_X86  -DUT_DIRECT_TRACE_REGISTRATION -DTR_HOST_X86 -c -o jswalk.o jswalk.c
In file included from jswalk.c:30:0:
../tr.source/trj9/runtime/MethodMetaData.h:381:18: error: inline function ‘getByteCodeInfo’ declared but never defined [-Werror]
 JITINLINE void * getByteCodeInfo(void *inlinedCallSite);
                  ^
Downgrading to gcc-4.8 fixes the issue.

Request that the code be made portable to newer compiler versions.

Thank you
      -p

**Comment by pshipton** [comment]
Considering the immediate problem is with the openj9 code, I suggest opening an issue on eclipse/openj9 would be more appropriate.

**Comment by andrew-m-leonard** [comment]
Please raise in github.com/eclipse/openj9
